### PR TITLE
Update package-lock.json to sync with new node version.

### PR DESCRIPTION
**Pull request by argoldbe**

### CODE REVIEW

**Review by phongcao — APPROVED** [review]

**Review by polatengin — APPROVED** [review]
thanks

**Review by mhassaninmsft — APPROVED** [review]
Curious how did you generate the new package-lock.json file
Did you delete the old one and re run npm install, or did you use a custom upgrade tool

**Comment by mhassaninmsft** [comment]
Also Everything is compiling locally fine without this change. All I need to do was delete node_modules since as you mention in your message it was generated by an older version of node/npm.

**Comment by argoldbe** [comment]
@mhassaninmsft Running npm install updated package-lock.json - specifically the lockfileVersion (and what I'm assuming is associated format changes) changes between the node versions we were using.

**Pull request merged**
